project_id = "qgurgdkkwyhwjddiovst"

[functions.paystack-webhook]
verify_jwt = false

[functions.pay-legend-article]
verify_jwt = true

[functions.pay-legend-tribute]
verify_jwt = false

[functions.admin-user-details]
verify_jwt = true

[functions.admin-user-action]
verify_jwt = true