// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhzmyiykidecbrfpzorx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoem15aXlraWRlY2JyZnB6b3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMzE3MjcsImV4cCI6MjA4ODkwNzcyN30.kHDrw1Xctb0AVsKM3UUF3QzEYgSi68Ypr1cff5uNaQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});